services:
  tictactoe:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tictactoe
    ports:
      - "9031:80"
    env_file:
      - ../.env
    environment:
      - PORT=80
      - CLOUD_HOST_NAME=cloud
      - NODE_ENV=production
    # restart: unless-stopped
    restart: "no"
    command: ["./scripts/docker-startup.sh", "bun", "run", "start"]

    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
